apiVersion: v1
kind: PersistentVolume
metadata:
  name: pavi-pv
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/var/log/pavi" 
