apiVersion: v1
kind: Service
metadata:
  labels:
    app: pavi-redis
  name: pavi-redis
spec:
  type: ClusterIP
  ports:
  - name: "pavi-redis-service"
    port: 6379
    targetPort: 6379
  selector:
    app: pavi-redis
