apiVersion: v1
kind: Service
metadata:
  labels:
    app: pavi-vote
  name: pavi-vote
spec:
  type: NodePort
  ports:
  - name: "pavi-vote-service"
    port: 5000
    targetPort: 80
    nodePort: 31000
  selector:
    app: pavi-vote
