apiVersion: v1
kind: Service
metadata:
  labels:
    app: pavi-worker
  name: pavi-worker
spec:
  type: ClusterIP
  ports:
  - name: "pavi-worker-service"
    port: 80
    targetPort: 80
  selector:
    app: pavi-postgres-db
